layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: adi.budithi
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: adibudithi
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: University of Illinois
    web_url: https://illinois.edu/
    image_url: images/Illinois_Block_I.png

  - name: Super Smash Bros
    web_url: https://www.smashbros.com/
    image_url: images/Smash_Ball.png

  - name: NBA
    web_url: hhttps://www.nba.com/
    image_url: images/nba_PNG2.png

theme: jekyll-theme-hacker
